name = "cbor"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A CBOR (RFC 8949) decoder/encoder library implemented pure Gleam"
licences = ["MIT"]
repository = { type = "github", user = "chiefnoah", repo = "cbor_gl" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "~> 0.36 or ~> 1.0"
rad = "~> 1.2"

[dev-dependencies]
gleeunit = "~> 1.0"
